name: vale-validation
on:
  pull_request:
    #types: [opened, reopened, synchronize]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
    # name: runner-vale
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #   #- uses: errata-ai/vale-action@reviewdog
    #   # id: check
    #   #with:
    #   # version: 2.17.0
    #   # github-pr-check, github-pr-review, github-check
    #   # reporter: github-pr-review
    #   #fail_on_error: true
    #   # added, diff_context, file, nofilter
    #   # filter_mode: nofilter
    #   - name: Get latest version of Vale
    #     id: lastversion
    #     uses: dvershinin/lastversion-action@main
    #     with:
    #       repository: errata-ai/vale-action

    #   - name: Install Vale
    #     run: |
    #       wget https://github.com/errata-ai/vale/releases/download/v${{ steps.lastversion.outputs.last_version }}/vale_${{ steps.lastversion.outputs.last_version }}_Linux_64-bit.tar.gz -O vale.tar.gz
    #       tar -xvzf vale.tar.gz vale
    #       rm vale.tar.gz

    #   #- name: Validate the syntax
    #   #  run: ./vale --config=.vale.ini *.md

    #   - name: Validate the syntax
    #     run: ./vale ./visual-kpi-docs/docs
